version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: brailleDB
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: IdkItsAPassword123!#2
    networks:
      - app-network
        #ports:
        #- "5432:5432"

  web:
    image: php:apache
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    ports:
      - "64550:80"
    networks:
      - app-network
    command: >
      bash -c "apt-get update && 
               apt-get install -y libpq-dev && 
               docker-php-ext-install pdo_pgsql &&
               apache2-foreground"

networks:
  app-network:
    driver: bridge
